public class area {

    public integer area(integer s){
        integer a= s*S;
        system.debug ('Area of square is : '+a);
        system.debug ('Area of square in SF org: '+a);
        return a;
    }
    public integer area(integer s1, integer s2){
        integer a=s1*s2;
        system.debug('area of rectangle is: '+a);
        return a;
    }
    public integer area(integer s1, integer s2, integer s3){
        integer a= s1*s2*s3;
        system.debug('area of 3 SIDED FIGURE is: '+a);
        return a;       
    }
}